// Core patient profile submitted by the clinician
export interface PatientProfile {
  age: number
  sex: "male" | "female" | "other"
  weightKg?: number
  heightCm?: number
  activityLevel: "sedentary" | "recreational" | "amateur" | "professional"
  sport?: string
  occupation?: string
  condition: string         // Main clinical condition / diagnosis
  injuryHistory?: string    // Previous treatments, surgeries, etc.
  symptomDuration?: string  // e.g. "6 months", "acute"
  failedTreatments?: string // What has already been tried
  clinicalArea: "physiotherapy" | "training" | "nutrition"
  additionalNotes?: string
}

// Structured PICOS derived from patient profile by AI
export interface PICOSQuery {
  population: string
  intervention: string
  comparison: string
  outcome: string
  studyDesign: string
  keywords: string[]
  searchQueries: {
    pubmed: string
    semantic: string
    general: string
  }
}

// A single paper result from any source
export interface Paper {
  id: string              // Internal dedup ID (DOI or generated)
  title: string
  authors: string[]
  year?: number
  journal?: string
  abstract?: string
  doi?: string
  pmid?: string
  url?: string
  openAccessUrl?: string
  source: SearchSource
  studyType?: string      // RCT, systematic review, cohort, etc.
  relevanceScore?: number // 0-100 scored by AI
  relevanceReason?: string
}

// Structured summary of a single paper generated by AI
export interface PaperSummary {
  paperId: string
  population: string
  intervention: string
  mainFindings: string
  clinicalRelevance: string  // Why this matters for this specific patient
  evidenceLevel: string
  limitations: string
}

// Full search session result
export interface SearchResult {
  id: string
  createdAt: string
  patientProfile: PatientProfile
  picos: PICOSQuery
  papers: Paper[]
  topPapers: Paper[]        // Top 10 after ranking
  evidenceSummary?: string  // AI narrative synthesis
  summaries: PaperSummary[]
  searchStats: {
    total: number
    bySource: Record<string, number>
    deduplicatedCount: number
  }
}

export type SearchSource =
  | "pubmed"
  | "semantic_scholar"
  | "openalex"
  | "europe_pmc"
  | "scielo"
  | "biorxiv"
  | "clinical_trials"
  | "core"
  | "pedro"

export type SearchStatus =
  | "idle"
  | "translating"   // AI converting patient → PICOS
  | "searching"     // Querying databases
  | "ranking"       // AI scoring relevance
  | "summarizing"   // AI generating summaries
  | "complete"
  | "error"
